version: "3"
services:
  docs_php_backend:
    build: docker/php_backend
    image: docs_php_backend:latest
    volumes:
      - .:/var/www
    restart: always
  docs_php_backend_debug:
    build: docker/php_backend_debug
    image: docs_php_backend_debug:latest
    volumes:
      - .:/var/www
    restart: always
  web_server:
    build: docker/web_server
    image: docs_web_server:latest
    command: ["/usr/sbin/nginx", "-c", "/etc/config/nginx.conf"]
    depends_on:
      - docs_php_backend
      - docs_php_backend_debug
    volumes:
      - .:/var/www
      - ./docker/web_server/config:/etc/config
    ports:
      - "80:8000"
    restart: always
