version: "3"
services:
  php_fpm:
    build: docker/php_fpm
    image: docs_php_fpm:latest
    labels:
      com.datadoghq.ad.logs: '[{"source": "php", "service": "docs_phpfpm"}]'
    volumes:
      - .:/var/www
      - ../keys.php:/var/keys.php
    restart: always
  php_fpm_debug:
    build: docker/php_fpm_debug
    image: docs_php_backend
    depends_on:
      - php_fpm
    volumes:
      - .:/var/www
    restart: always
  nginx:
    build: docker/nginx
    depends_on:
      - php_fpm
      - php_fpm_debug
    volumes:
      - .:/var/www
    restart: always
